<<<<<<< HEAD
// flow-typed signature: 8e750467264db8902d62c0dee06c4cf1
// flow-typed version: <<STUB>>/prettier_v1.3.1/flow_v0.47.0
=======
// flow-typed signature: 31fcbe68d612f0f18fbeddb9c03fae79
// flow-typed version: <<STUB>>/prettier_v1.7.0/flow_v0.47.0
>>>>>>> v3-11

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier/bin/prettier' {
  declare module.exports: any;
}

<<<<<<< HEAD
declare module 'prettier/docs/prettier.min' {
  declare module.exports: any;
}

declare module 'prettier/docs/rollup.config' {
  declare module.exports: any;
}

declare module 'prettier/scripts/sync-flow-tests' {
  declare module.exports: any;
}

declare module 'prettier/src/ast-types' {
  declare module.exports: any;
}

declare module 'prettier/src/comments' {
  declare module.exports: any;
}

declare module 'prettier/src/deprecated' {
  declare module.exports: any;
}

declare module 'prettier/src/doc-builders' {
  declare module.exports: any;
}

declare module 'prettier/src/doc-debug' {
  declare module.exports: any;
}

declare module 'prettier/src/doc-printer' {
  declare module.exports: any;
}

declare module 'prettier/src/doc-utils' {
  declare module.exports: any;
}

declare module 'prettier/src/fast-path' {
  declare module.exports: any;
}

declare module 'prettier/src/options' {
  declare module.exports: any;
}

declare module 'prettier/src/parser' {
  declare module.exports: any;
}

declare module 'prettier/src/printer' {
  declare module.exports: any;
}

declare module 'prettier/src/typescript-ast-nodes' {
  declare module.exports: any;
}

declare module 'prettier/src/util' {
  declare module.exports: any;
}

declare module 'prettier/test' {
=======
declare module 'prettier/parser-babylon' {
  declare module.exports: any;
}

declare module 'prettier/parser-flow' {
  declare module.exports: any;
}

declare module 'prettier/parser-graphql' {
  declare module.exports: any;
}

declare module 'prettier/parser-parse5' {
  declare module.exports: any;
}

declare module 'prettier/parser-postcss' {
  declare module.exports: any;
}

declare module 'prettier/parser-typescript' {
>>>>>>> v3-11
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier/bin/prettier.js' {
  declare module.exports: $Exports<'prettier/bin/prettier'>;
}
<<<<<<< HEAD
declare module 'prettier/docs/prettier.min.js' {
  declare module.exports: $Exports<'prettier/docs/prettier.min'>;
}
declare module 'prettier/docs/rollup.config.js' {
  declare module.exports: $Exports<'prettier/docs/rollup.config'>;
}
=======
>>>>>>> v3-11
declare module 'prettier/index' {
  declare module.exports: $Exports<'prettier'>;
}
declare module 'prettier/index.js' {
  declare module.exports: $Exports<'prettier'>;
}
<<<<<<< HEAD
declare module 'prettier/scripts/sync-flow-tests.js' {
  declare module.exports: $Exports<'prettier/scripts/sync-flow-tests'>;
}
declare module 'prettier/src/ast-types.js' {
  declare module.exports: $Exports<'prettier/src/ast-types'>;
}
declare module 'prettier/src/comments.js' {
  declare module.exports: $Exports<'prettier/src/comments'>;
}
declare module 'prettier/src/deprecated.js' {
  declare module.exports: $Exports<'prettier/src/deprecated'>;
}
declare module 'prettier/src/doc-builders.js' {
  declare module.exports: $Exports<'prettier/src/doc-builders'>;
}
declare module 'prettier/src/doc-debug.js' {
  declare module.exports: $Exports<'prettier/src/doc-debug'>;
}
declare module 'prettier/src/doc-printer.js' {
  declare module.exports: $Exports<'prettier/src/doc-printer'>;
}
declare module 'prettier/src/doc-utils.js' {
  declare module.exports: $Exports<'prettier/src/doc-utils'>;
}
declare module 'prettier/src/fast-path.js' {
  declare module.exports: $Exports<'prettier/src/fast-path'>;
}
declare module 'prettier/src/options.js' {
  declare module.exports: $Exports<'prettier/src/options'>;
}
declare module 'prettier/src/parser.js' {
  declare module.exports: $Exports<'prettier/src/parser'>;
}
declare module 'prettier/src/printer.js' {
  declare module.exports: $Exports<'prettier/src/printer'>;
}
declare module 'prettier/src/typescript-ast-nodes.js' {
  declare module.exports: $Exports<'prettier/src/typescript-ast-nodes'>;
}
declare module 'prettier/src/util.js' {
  declare module.exports: $Exports<'prettier/src/util'>;
}
declare module 'prettier/test.js' {
  declare module.exports: $Exports<'prettier/test'>;
=======
declare module 'prettier/parser-babylon.js' {
  declare module.exports: $Exports<'prettier/parser-babylon'>;
}
declare module 'prettier/parser-flow.js' {
  declare module.exports: $Exports<'prettier/parser-flow'>;
}
declare module 'prettier/parser-graphql.js' {
  declare module.exports: $Exports<'prettier/parser-graphql'>;
}
declare module 'prettier/parser-parse5.js' {
  declare module.exports: $Exports<'prettier/parser-parse5'>;
}
declare module 'prettier/parser-postcss.js' {
  declare module.exports: $Exports<'prettier/parser-postcss'>;
}
declare module 'prettier/parser-typescript.js' {
  declare module.exports: $Exports<'prettier/parser-typescript'>;
>>>>>>> v3-11
}
